### ISSUE TITLE
I got the "must be equal to input_size error" message.

### ISSUE THREAD

**Issue by pdc-kaminaga** [shakeel608/OpenNMT-py-with-BERT#5]
I got the "must be equal to input_size error" message.
Please tell me how to deal with this problem.
I used OpenNMT-py / data.

mscOS: 10.15.2
Python: 3.7.5rc1
torch: 1.0.0
torchvision: 0.2.1

$ time python preprocess.py -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo

[2020-01-12 10:29:17,834 INFO] Extracting features...
[2020-01-12 10:29:17,834 INFO]  * number of source features: 0.
[2020-01-12 10:29:17,834 INFO]  * number of target features: 0.
[2020-01-12 10:29:17,834 INFO] Building `Fields` object...
[2020-01-12 10:29:17,835 INFO] Building & saving training data...
[2020-01-12 10:29:17,835 INFO] Reading source and target files: data/src-train.txt data/tgt-train.txt.
[2020-01-12 10:29:17,838 INFO] Building shard 0.
[2020-01-12 10:29:21,220 INFO]  * saving 0th train data shard to data/demo.train.0.pt.
[2020-01-12 10:29:21,640 INFO] Building & saving validation data...
[2020-01-12 10:29:21,640 INFO] Reading source and target files: data/src-val.txt data/tgt-val.txt.
[2020-01-12 10:29:21,642 INFO] Building shard 0.
[2020-01-12 10:29:22,717 INFO]  * saving 0th valid data shard to data/demo.valid.0.pt.
[2020-01-12 10:29:22,857 INFO] Building & saving vocabulary...
[2020-01-12 10:29:22,935 INFO]  * reloading data/demo.train.0.pt.
[2020-01-12 10:29:23,156 INFO]  * tgt vocab size: 33329.
[2020-01-12 10:29:23,183 INFO]  * src vocab size: 14863.

real        0m14.890s
user        0m9.505s
sys        0m0.912s

$ time python train.py -data data/demo -save_model demo-model 
[2020-01-12 10:30:12,973 INFO]  * src vocab size = 14863
[2020-01-12 10:30:12,973 INFO]  * tgt vocab size = 33329
[2020-01-12 10:30:12,973 INFO] Building model...
[2020-01-12 10:30:13,467 INFO] NMTModel(
  (encoder): RNNEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(14863, 500, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(500, 500, num_layers=2, dropout=0.3)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(33329, 500, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.3)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.3)
      (layers): ModuleList(
        (0): LSTMCell(1000, 500)
        (1): LSTMCell(500, 500)
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=500, out_features=500, bias=False)
      (linear_out): Linear(in_features=1000, out_features=500, bias=False)
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=500, out_features=33329, bias=True)
    (1): Cast()
    (2): LogSoftmax()
  )
)
[2020-01-12 10:30:13,467 INFO] encoder: 11439500
[2020-01-12 10:30:13,467 INFO] decoder: 39120329
[2020-01-12 10:30:13,467 INFO] * number of parameters: 50559829
[2020-01-12 10:30:13,468 INFO] Starting training on CPU, could be very slow
[2020-01-12 10:30:13,468 INFO] Start training loop and validate every 10000 steps...
[2020-01-12 10:30:13,534 INFO] Loading dataset from data/demo.train.0.pt, number of examples: 9554
Traceback (most recent call last):
  File "train.py", line 109, in <module>
    main(opt)
  File "train.py", line 41, in main
    single_main(opt, -1)
  File "/Users/kami/Documents/mlearn/OpenNMT-py-with-BERT/onmt/train_single.py", line 116, in main
    valid_steps=opt.valid_steps)
  File "/Users/kami/Documents/mlearn/OpenNMT-py-with-BERT/onmt/trainer.py", line 209, in train
    report_stats)
  File "/Users/kami/Documents/mlearn/OpenNMT-py-with-BERT/onmt/trainer.py", line 318, in _gradient_accumulation
    outputs, attns = self.model(src, tgt, src_lengths, bptt=bptt)
  File "/Users/kami/python_env/OpenNMT-py-with-BERT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/kami/Documents/mlearn/OpenNMT-py-with-BERT/onmt/models/model.py", line 42, in forward
    enc_state, memory_bank, lengths = self.encoder(src, lengths)
  File "/Users/kami/python_env/OpenNMT-py-with-BERT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/kami/Documents/mlearn/OpenNMT-py-with-BERT/onmt/encoders/rnn_encoder.py", line 82, in forward
    memory_bank, encoder_final = self.rnn(packed_emb)
  File "/Users/kami/python_env/OpenNMT-py-with-BERT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/kami/python_env/OpenNMT-py-with-BERT/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 175, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/Users/kami/python_env/OpenNMT-py-with-BERT/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 135, in check_forward_args
    self.input_size, input.size(-1)))
RuntimeError: input.size(-1) must be equal to input_size. Expected 500, got 768

**Comment by pdc-kaminaga** [comment]
I should use --rnn_size,  --word_vec_size.
Thank you.
